---
# handlers file for sosreport
- name: restart sosreport
  service:
    name: "{{ sosreport_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker" or sosreport_ignore_docker
